title: Sneha Bhambri
logo: docs/assets/ -7.jpg
description: Hi! I'm a criminal justice researcher with experience spanning across academia and consultancy.
#show_downloads: true
theme: jekyll-theme-minimal
