title: Sneha Bhambri
logo: /assets/img/logo.png
description: Hi! I'm a criminal and youth justice researcher with experience spanning across academia and consultancy.
show_downloads: true
theme: jekyll-theme-minimal
