title: Sneha Bhambri
logo: docs/assets/2232debe-4003-4d09-8c55-3f50dba06918.JPG
description: Hi! I'm a criminal justice researcher with experience spanning across academia and consultancy.
#show_downloads: true
theme: jekyll-theme-minimal
